//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubberduck.Resources.v3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogsUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogsUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rubberduck.Resources.v3.DialogsUI", typeof(DialogsUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File.
        /// </summary>
        public static string AddFile_Title {
            get {
                return ResourceManager.GetString("AddFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Visual Basic class module with the default configuration for a VBA class, including &apos;Option Explicit&apos;..
        /// </summary>
        public static string FileTemplate_ClsModuleVBA_Description {
            get {
                return ResourceManager.GetString("FileTemplate_ClsModuleVBA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Module.
        /// </summary>
        public static string FileTemplate_ClsModuleVBA_Name {
            get {
                return ResourceManager.GetString("FileTemplate_ClsModuleVBA_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Visual Basic form class module with &apos;Option Explicit&apos; specified..
        /// </summary>
        public static string FileTemplate_FrmModuleVBA_Description {
            get {
                return ResourceManager.GetString("FileTemplate_FrmModuleVBA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserForm Module.
        /// </summary>
        public static string FileTemplate_FrmModuleVBA_Name {
            get {
                return ResourceManager.GetString("FileTemplate_FrmModuleVBA_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A human-readable data file..
        /// </summary>
        public static string FileTemplate_JsonDocument_Description {
            get {
                return ResourceManager.GetString("FileTemplate_JsonDocument_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON File.
        /// </summary>
        public static string FileTemplate_JsonDocument_Name {
            get {
                return ResourceManager.GetString("FileTemplate_JsonDocument_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A formatted text document..
        /// </summary>
        public static string FileTemplate_MarkdownDocument_Description {
            get {
                return ResourceManager.GetString("FileTemplate_MarkdownDocument_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Document.
        /// </summary>
        public static string FileTemplate_MarkdownDocument_Name {
            get {
                return ResourceManager.GetString("FileTemplate_MarkdownDocument_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A standard procedural Visual Basic module, with &apos;Option Explicit&apos; specified..
        /// </summary>
        public static string FileTemplate_StdModule_Description {
            get {
                return ResourceManager.GetString("FileTemplate_StdModule_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Module.
        /// </summary>
        public static string FileTemplate_StdModule_Name {
            get {
                return ResourceManager.GetString("FileTemplate_StdModule_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Visual Basic class module with the default configuration for a VBA class, including &apos;Option Explicit&apos; and with @OptionStrict language server rules enabled..
        /// </summary>
        public static string FileTemplate_StrictClsModuleVBA_Description {
            get {
                return ResourceManager.GetString("FileTemplate_StrictClsModuleVBA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Module (Strict).
        /// </summary>
        public static string FileTemplate_StrictClsModuleVBA_Name {
            get {
                return ResourceManager.GetString("FileTemplate_StrictClsModuleVBA_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Visual Basic form class module with &apos;Option Explicit&apos; specified and @OptionStrict language server rules enabled..
        /// </summary>
        public static string FileTemplate_StrictFrmModuleVBA_Description {
            get {
                return ResourceManager.GetString("FileTemplate_StrictFrmModuleVBA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserForm Module (Strict).
        /// </summary>
        public static string FileTemplate_StrictFrmModuleVBA_Name {
            get {
                return ResourceManager.GetString("FileTemplate_StrictFrmModuleVBA_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A standard procedural Visual Basic module, with &apos;Option Explicit&apos; specified and @OptionStrict language server rules enabled..
        /// </summary>
        public static string FileTemplate_StrictStdModule_Description {
            get {
                return ResourceManager.GetString("FileTemplate_StrictStdModule_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Module (Strict).
        /// </summary>
        public static string FileTemplate_StrictStdModule_Name {
            get {
                return ResourceManager.GetString("FileTemplate_StrictStdModule_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple text document..
        /// </summary>
        public static string FileTemplate_TextDocument_Description {
            get {
                return ResourceManager.GetString("FileTemplate_TextDocument_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Document.
        /// </summary>
        public static string FileTemplate_TextDocument_Name {
            get {
                return ResourceManager.GetString("FileTemplate_TextDocument_Name", resourceCulture);
            }
        }
    }
}
